version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 130904
      MYSQL_DATABASE: ntp_booking_movie  # Tạo database khi khởi động
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./ntpticketdb.sql:/docker-entrypoint-initdb.d/init.sql  # Ánh xạ file SQL vào container

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ntp_booking_movie
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=130904

volumes:
  mysql_data:
